/* Generated by Yosys 0.10.0 (git sha1 UNKNOWN, gcc 11.1.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

(* hdlname = "\\top_lvl" *)
(* top =  1  *)
(* src = "./yeet.v:1.1-8.10" *)
module top_lvl(a, b, s, y);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "./yeet.v:2.16-2.17" *)
  input a;
  (* src = "./yeet.v:2.19-2.20" *)
  input b;
  (* src = "./yeet.v:2.22-2.23" *)
  input s;
  (* src = "./yeet.v:3.17-3.18" *)
  output y;
  NOT _3_ (
    .A(s),
    .Y(_0_)
  );
  NAND _4_ (
    .A(a),
    .B(s),
    .Y(_1_)
  );
  NAND _5_ (
    .A(b),
    .B(_0_),
    .Y(_2_)
  );
  NAND _6_ (
    .A(_1_),
    .B(_2_),
    .Y(y)
  );
endmodule
